/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 modern_living_room.glb 
Author: Visthétique (https://sketchfab.com/visthetique)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-living-room-ec7179648b1e43739104994d64e95673
Title: Modern Living Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/modern_living_room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.252}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[118.743, 916.667, -267.474]} rotation={[-Math.PI / 2, 0, 0]} scale={43.269}>
            <mesh geometry={nodes.AloeVera_Pot_0.geometry} material={materials.material} />
            <mesh geometry={nodes.AloeVera_Dirt_0.geometry} material={materials.Dirt} />
            <mesh geometry={nodes.AloeVera_AloeVera_0.geometry} material={materials.AloeVera} />
          </group>
          <group position={[264.038, 1857.946, 1189.746]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Ceiling_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Ceiling_Walls_0.geometry} material={materials.Walls} />
            <mesh geometry={nodes.Ceiling_SyntticWood_0.geometry} material={materials.SyntticWood} />
          </group>
          <group position={[-671.552, 281.98, 1266.563]} rotation={[-Math.PI / 2, 0, 0]} scale={109.433}>
            <mesh geometry={nodes.Couch_Back_Pillows_0.geometry} material={materials.Back_Pillows} />
            <mesh geometry={nodes.Couch_Front_Pillows_0.geometry} material={materials.Front_Pillows} />
            <mesh geometry={nodes.Couch_Couch_0.geometry} material={materials.Couch} />
            <mesh geometry={nodes.Couch_Pique_0.geometry} material={materials.Pique} />
          </group>
          <group position={[1048.553, 40.85, 1337.634]} rotation={[-Math.PI, 0, -Math.PI]} scale={[14.979, 14.979, 17.259]}>
            <mesh geometry={nodes.Curtain__97_0.geometry} material={materials.material_14} />
            <mesh geometry={nodes.Curtain_Color_001_0.geometry} material={materials.Color_001} />
          </group>
          <group position={[-128.644, 554.282, -284.096]} rotation={[-Math.PI / 2, 0, 0]} scale={23.53}>
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_18_3683_0.geometry} material={materials.M_002_Mat3d66_1273812_18_3683} />
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_18_3683_0_1.geometry} material={materials.M_002_Mat3d66_1273812_18_3683} />
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_18_3683_0_2.geometry} material={materials.M_002_Mat3d66_1273812_18_3683} />
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_5_6883_0.geometry} material={materials.M_002_Mat3d66_1273812_5_6883} />
            <mesh geometry={nodes.D1001_GlassD1_0.geometry} material={materials.GlassD1} />
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_6_9985_0.geometry} material={materials.M_002_Mat3d66_1273812_6_9985} />
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_7_8078_0.geometry} material={materials.M_002_Mat3d66_1273812_7_8078} />
            <mesh geometry={nodes.D1001_M_002_Mat3d66_1273812_5_6883_1__0.geometry} material={materials.M_002_Mat3d66_1273812_5_6883_1} />
            <mesh geometry={nodes.D1001_Steel_Polished_0.geometry} material={materials.Steel_Polished} />
            <mesh geometry={nodes.D1001_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.D1001_Black_0.geometry} material={materials.Black} />
          </group>
          <group position={[163.69, 808.748, -286.27]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_18_3683_0.geometry} material={materials.M_002_Mat3d66_1273812_18_3683} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_18_3683_0_1.geometry} material={materials.M_002_Mat3d66_1273812_18_3683} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_18_3683_0_2.geometry} material={materials.M_002_Mat3d66_1273812_18_3683} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_5_6883_0.geometry} material={materials.M_002_Mat3d66_1273812_5_6883} />
            <mesh geometry={nodes.D1002_GlassD1_0.geometry} material={materials.GlassD1} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_6_9985_0.geometry} material={materials.M_002_Mat3d66_1273812_6_9985} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_7_8078_0.geometry} material={materials.M_002_Mat3d66_1273812_7_8078} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_5_6883_1__0.geometry} material={materials.M_002_Mat3d66_1273812_5_6883_1} />
            <mesh geometry={nodes.D1002_Gold_14k_0.geometry} material={materials.Gold_14k} />
            <mesh geometry={nodes.D1002_M_002_Mat3d66_1273812_4_3309_0.geometry} material={materials.M_002_Mat3d66_1273812_4_3309} />
          </group>
          <group position={[-82.857, 953.599, -288.501]} rotation={[-Math.PI / 2, 0, 0]} scale={25.051}>
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_11_2985_0.geometry} material={materials.M_002_Mat3d66_1273812_11_2985} />
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_9_4605_0.geometry} material={materials.M_002_Mat3d66_1273812_9_4605} />
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_9_4605_0_1.geometry} material={materials.M_002_Mat3d66_1273812_9_4605} />
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_10_1221_0.geometry} material={materials.M_002_Mat3d66_1273812_10_1221} />
            <mesh geometry={nodes.D1008_GlassD1_0.geometry} material={materials.GlassD1} />
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_15_3004_0.geometry} material={materials.M_002_Mat3d66_1273812_15_3004} />
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_16_182_0.geometry} material={materials.M_002_Mat3d66_1273812_16_182} />
            <mesh geometry={nodes.D1008_M_002_Mat3d66_1273812_17_8628_0.geometry} material={materials.M_002_Mat3d66_1273812_17_8628} />
            <mesh geometry={nodes.D1008_Iron_Blurry_5cm_0.geometry} material={materials.Iron_Blurry_5cm} />
            <mesh geometry={nodes.D1008_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.D1008_Steel_Polished_0.geometry} material={materials.Steel_Polished} />
          </group>
          <group position={[447.793, 415.892, -252.09]} rotation={[-Math.PI / 2, 0, 0]} scale={31.435}>
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_11_2985_0.geometry} material={materials.M_002_Mat3d66_1273812_11_2985} />
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_9_4605_0.geometry} material={materials.M_002_Mat3d66_1273812_9_4605} />
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_9_4605_0_1.geometry} material={materials.M_002_Mat3d66_1273812_9_4605} />
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_10_1221_0.geometry} material={materials.M_002_Mat3d66_1273812_10_1221} />
            <mesh geometry={nodes.D1011_GlassD1_0.geometry} material={materials.GlassD1} />
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_15_3004_0.geometry} material={materials.M_002_Mat3d66_1273812_15_3004} />
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_16_182_0.geometry} material={materials.M_002_Mat3d66_1273812_16_182} />
            <mesh geometry={nodes.D1011_M_002_Mat3d66_1273812_17_8628_0.geometry} material={materials.M_002_Mat3d66_1273812_17_8628} />
            <mesh geometry={nodes.D1011_Iron_Blurry_5cm_0.geometry} material={materials.Iron_Blurry_5cm} />
            <mesh geometry={nodes.D1011_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.D1011_Steel_Polished_0.geometry} material={materials.Steel_Polished} />
          </group>
          <group position={[-1034.096, 531.327, -263.121]} rotation={[-Math.PI / 2, 0, 0]} scale={24.04}>
            <mesh geometry={nodes.D1013_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.D1013_M_002_Mat3d66_1273812_1_8130_0.geometry} material={materials.M_002_Mat3d66_1273812_1_8130} />
            <mesh geometry={nodes.D1013_M_002_Mat3d66_1273812_2_5410_0.geometry} material={materials.M_002_Mat3d66_1273812_2_5410} />
          </group>
          <group position={[-69.397, 1534.445, -281.089]} rotation={[-Math.PI / 2, 0, 0]} scale={33.755}>
            <mesh geometry={nodes.D2_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.D2_Concrete034_0.geometry} material={materials.Concrete034} />
            <mesh geometry={nodes.D2_Gold_14k_0.geometry} material={materials.Gold_14k} />
            <mesh geometry={nodes.D2_Concrete030_0.geometry} material={materials.Concrete030} />
            <mesh geometry={nodes.D2_Material__8_0.geometry} material={materials.Material__8} />
            <mesh geometry={nodes.D2_dssd4_0.geometry} material={materials.dssd4} />
            <mesh geometry={nodes.D2_Material__2147448381_0.geometry} material={materials.Material__2147448381} />
            <mesh geometry={nodes.D2_Material__214723445232_0.geometry} material={materials.Material__214723445232} />
          </group>
          <group position={[-25.458, 1262.543, -259.463]} rotation={[-Math.PI / 2, 0, 0]} scale={38.664}>
            <mesh geometry={nodes.D2001_Material__6_0.geometry} material={materials.Material__6} />
            <mesh geometry={nodes.D2001_Material__2_0.geometry} material={materials.Material__2} />
            <mesh geometry={nodes.D2001_Material__21474452232_0.geometry} material={materials.Material__21474452232} />
            <mesh geometry={nodes.D2001___2_0.geometry} material={materials.material_44} />
            <mesh geometry={nodes.D2001_Material__5_0.geometry} material={materials.Material__5} />
            <mesh geometry={nodes.D2001_Concrete030_0.geometry} material={materials.Concrete030} />
            <mesh geometry={nodes.D2001_Concrete034_0.geometry} material={materials.Concrete034} />
            <mesh geometry={nodes.D2001_Material__2147448380_0.geometry} material={materials.Material__2147448380} />
          </group>
          <group position={[-844.81, 698.028, -254.423]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.D2002_Material__241_0.geometry} material={materials.Material__241} />
            <mesh geometry={nodes.D2002_Concrete034_0.geometry} material={materials.Concrete034} />
            <mesh geometry={nodes.D2002_Gold_14k_0.geometry} material={materials.Gold_14k} />
            <mesh geometry={nodes.D2002_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.D2002_Concrete030_0.geometry} material={materials.Concrete030} />
          </group>
          <group position={[-548.13, 387.704, -246.755]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.D2005_Material__241_0.geometry} material={materials.Material__241} />
            <mesh geometry={nodes.D2005_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.D2005_Concrete030_0.geometry} material={materials.Concrete030} />
            <mesh geometry={nodes.D2005_Gold_14k_0.geometry} material={materials.Gold_14k} />
            <mesh geometry={nodes.D2005_Concrete034_0.geometry} material={materials.Concrete034} />
          </group>
          <group position={[-100.596, 267.156, 1626.135]} rotation={[-1.559, -0.02, 0]} scale={288.064}>
            <mesh geometry={nodes.D3_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.D3_Material__7001_0.geometry} material={materials['Material__7.001']} />
            <mesh geometry={nodes.D3_Material__1001_0.geometry} material={materials['Material__1.001']} />
            <mesh geometry={nodes.D3_GlassD1_0.geometry} material={materials.GlassD1} />
            <mesh geometry={nodes.D3__27_0.geometry} material={materials.material_50} />
            <mesh geometry={nodes.D3_Liquid_0.geometry} material={materials.Liquid} />
            <mesh geometry={nodes.D3_rotulo_03_difusor_0.geometry} material={materials.rotulo_03_difusor} />
            <mesh geometry={nodes.D3_rotulo_01_difusor_0.geometry} material={materials.rotulo_01_difusor} />
            <mesh geometry={nodes.D3_madeira_palitos_difusor_0.geometry} material={materials.madeira_palitos_difusor} />
          </group>
          <group position={[-932.564, 37.218, 206.378]} rotation={[-Math.PI / 2, 0, 0.254]} scale={127.858}>
            <mesh geometry={nodes.Ficus_Elastica_Leaf1_0.geometry} material={materials.Leaf1} />
            <mesh geometry={nodes.Ficus_Elastica_Sapling_0.geometry} material={materials.Sapling} />
            <mesh geometry={nodes.Ficus_Elastica_Leaf2_0.geometry} material={materials.Leaf2} />
            <mesh geometry={nodes.Ficus_Elastica_Pot2_0.geometry} material={materials.Pot2} />
            <mesh geometry={nodes.Ficus_Elastica_Dirt2_0.geometry} material={materials.Dirt2} />
          </group>
          <group position={[312.251, 211.011, 2707.546]} rotation={[-Math.PI / 2, 0, 0]} scale={179.437}>
            <mesh geometry={nodes.Fireplace_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Fireplace_GlassD1_0.geometry} material={materials.GlassD1} />
          </group>
          <group position={[344.03, 303.581, 2635.483]} rotation={[-Math.PI / 2, 0, 0]} scale={36.795}>
            <mesh geometry={nodes.Logs_Modern_Fireplace_Material1_0.geometry} material={materials.Modern_Fireplace_Material1} />
            <mesh geometry={nodes.Logs_Modern_Fireplace_Material_0.geometry} material={materials.Modern_Fireplace_Material} />
            <mesh geometry={nodes.Logs_Modern_Fireplace_Material4_0.geometry} material={materials.Modern_Fireplace_Material4} />
          </group>
          <group position={[-119.753, 722.987, -274.26]} rotation={[-Math.PI, 0, -Math.PI]} scale={102.159}>
            <mesh geometry={nodes.POTHOS_POTHOS_Mat_0.geometry} material={materials.POTHOS_Mat} />
            <mesh geometry={nodes.POT_WOOD_LEGS_WOODEN_LEGS_POT_0.geometry} material={materials.WOODEN_LEGS_POT} position={[-0.01, -0.943, -0.055]} rotation={[-Math.PI / 2, 0, 0]} scale={1.925} />
          </group>
          <group position={[-1134.219, 1047.42, 1364.625]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[370.993, 10.429, 584.497]}>
            <mesh geometry={nodes.Painting_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Painting_Painting_0.geometry} material={materials.Painting} />
            <mesh geometry={nodes.Painting_GlassD1_0.geometry} material={materials.GlassD1} />
          </group>
          <group position={[-939.775, 324.002, 2673.192]} rotation={[-Math.PI / 2, 0, 0.441]} scale={363.07}>
            <mesh geometry={nodes.Peace_Lily_LilyMetal_0.geometry} material={materials.LilyMetal} />
            <mesh geometry={nodes.Peace_Lily_LilyPorcelain_0.geometry} material={materials.LilyPorcelain} />
            <mesh geometry={nodes.Peace_Lily_lilysoil_0.geometry} material={materials.lilysoil} />
            <mesh geometry={nodes.Peace_Lily_LilyGreen_0.geometry} material={materials.LilyGreen} />
            <mesh geometry={nodes.Peace_Lily_TCom_Plant_PeaceLily02_2K_albedo_0.geometry} material={materials.TCom_Plant_PeaceLily02_2K_albedo} />
          </group>
          <group position={[-0.519, 40.85, -337.821]} rotation={[-Math.PI / 2, 0, 0]} scale={[139.734, 100, 100]}>
            <mesh geometry={nodes.Plane_Walls_0.geometry} material={materials.Walls} />
            <mesh geometry={nodes.Plane_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Plane_Wall2_0.geometry} material={materials.Wall2} />
            <mesh geometry={nodes.Plane_Floor_0.geometry} material={materials.Floor} />
          </group>
          <group position={[1001.67, 1838.948, 3062.611]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Spotlights_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Spotlights_SpotlightLight_0.geometry} material={materials.SpotlightLight} />
          </group>
          <mesh geometry={nodes.Baseboard_White_0.geometry} material={materials.White} position={[-1.607, 60.984, 2258.373]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Bookcase_Bookcase_0.geometry} material={materials.Bookcase} position={[-776.848, 591.55, -267.171]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Books_Books_0.geometry} material={materials.Books} position={[397.704, 50.192, 856.561]} rotation={[0, -0.404, 0]} scale={7.195} />
          <mesh geometry={nodes.Cube001_Stairs_0.geometry} material={materials.Stairs} position={[237.582, 660.826, -428.646]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.CylinderDecor_CylinderDecor_0.geometry} material={materials.CylinderDecor} position={[-834.134, 127.69, 2494.708]} rotation={[-Math.PI / 2, 0, 0]} scale={[60.599, 60.599, 87.821]} />
          <mesh geometry={nodes.D1_Concrete034_0.geometry} material={materials.Concrete034} position={[368.362, 805.17, -257.507]} rotation={[-Math.PI / 2, 0, 0]} scale={31.435} />
          <mesh geometry={nodes.D1004_Gold_14k_0.geometry} material={materials.Gold_14k} position={[130.828, 425.944, -267.428]} rotation={[-Math.PI / 2, 0, 0]} scale={31.435} />
          <mesh geometry={nodes.FloorPillow_Floor_Pillow_0.geometry} material={materials.Floor_Pillow} position={[-63.028, 124.399, 2423.384]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ModernLamps_ModernLamps_0.geometry} material={materials.ModernLamps} position={[-947.163, 1317.742, 1387.342]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rug_Rug_0.geometry} material={materials.material_75} position={[-149.719, 69.518, 1705.304]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Shelfs_Shelfs_0.geometry} material={materials.Shelfs} position={[71.946, 850.945, -272.76]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.SphereDecor_SphereDecor_0.geometry} material={materials.SphereDecor} position={[-674.329, 99.035, 2570.35]} rotation={[-Math.PI / 2, 0, 0]} scale={124.484} />
          <mesh geometry={nodes.Window_Window_0.geometry} material={materials.Window} position={[1177.336, 909.143, 1364.881]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.WoodCoffeTable_WoodCoffeTable_0.geometry} material={materials.WoodCoffeTable} position={[-81.07, 151.158, 1675.818]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/modern_living_room.glb')
