/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 office.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { EffectComposer, Bloom } from '@react-three/postprocessing'


export function Office(props) {
  const { nodes, materials } = useGLTF('/models/office.glb')
  return (
    <group {...props} dispose={null}>
      <EffectComposer>
        <Bloom
          intensity={9}
          luminanceThreshold={0.1}
          luminanceSmoothing={1}
        />
      </EffectComposer>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-123.493, 1.133, 64.664]} rotation={[-Math.PI / 2, 0, -2.988]} scale={100}>
            <mesh geometry={nodes.Archinteriors8_01_292003_Esmalte_Preto001_0.geometry} material={materials['Esmalte_Preto.001']} />
            <mesh geometry={nodes.Archinteriors8_01_292003_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group position={[83.984, 227.115, 272.869]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[109.964, 109.963, 109.963]}>
            <mesh geometry={nodes.books005_books003_0.geometry} material={materials['books.003']} />
            <mesh geometry={nodes.books005_bookspaper002_0.geometry} material={materials['books.paper.002']} />
          </group>
          <group position={[108.26, 44.492, -116.527]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.659, 3.09, 3.015]}>
            <mesh geometry={nodes.Box323536001_Cabinet_color001_0.geometry} material={materials['Cabinet_color.001']} />
            <mesh geometry={nodes.Box323536001_Cabinet_Handle001_0.geometry} material={materials['Cabinet_Handle.001']} />
            <mesh geometry={nodes.Box323536001_Cabinet_Wood001_0.geometry} material={materials['Cabinet_Wood.001']} />
          </group>
          <group position={[-39.701, 109.763, 134.386]} rotation={[-Math.PI / 2, 0, 0]} scale={7.178}>
            <mesh geometry={nodes.Circle001_PC1GlossyPin001_0.geometry} material={materials['PC1GlossyPin.001']} />
            <mesh geometry={nodes.Circle001_PC1Material008_0.geometry} material={materials['PC1Material.008']} />
            <mesh geometry={nodes.Circle001_PC1Material009_0.geometry} material={materials['PC1Material.009']} />
            <mesh geometry={nodes.Circle001_PC1Material015_0.geometry} material={materials['PC1Material.015']} />
            <mesh geometry={nodes.Circle001_PC1Material016_0.geometry} material={materials['PC1Material.016']} />
            <mesh geometry={nodes.Circle001_PC1PenBlackpart001_0.geometry} material={materials['PC1PenBlackpart.001']} />
            <mesh geometry={nodes.Circle001_PC1PenGlossyPart1001_0.geometry} material={materials['PC1PenGlossyPart1.001']} />
            <mesh geometry={nodes.Circle001_PC1WireInGlas_0.geometry} material={materials.PC1WireInGlas} />
          </group>
          <group position={[6.5, 109.763, -135.082]} rotation={[-Math.PI / 2, 0, 0]} scale={7.178}>
            <mesh geometry={nodes.Circle002_PC1GlossyPin001_0.geometry} material={materials['PC1GlossyPin.001']} />
            <mesh geometry={nodes.Circle002_PC1Material008_0.geometry} material={materials['PC1Material.008']} />
            <mesh geometry={nodes.Circle002_PC1Material009_0.geometry} material={materials['PC1Material.009']} />
            <mesh geometry={nodes.Circle002_PC1Material015_0.geometry} material={materials['PC1Material.015']} />
            <mesh geometry={nodes.Circle002_PC1Material016_0.geometry} material={materials['PC1Material.016']} />
            <mesh geometry={nodes.Circle002_PC1PenBlackpart001_0.geometry} material={materials['PC1PenBlackpart.001']} />
            <mesh geometry={nodes.Circle002_PC1PenGlossyPart1001_0.geometry} material={materials['PC1PenGlossyPart1.001']} />
            <mesh geometry={nodes.Circle002_PC1WireInGlas_0.geometry} material={materials.PC1WireInGlas} />
          </group>
          <group position={[414.959, 364.929, 481.161]} rotation={[-Math.PI / 2, 0, 0]} scale={5.07}>
            <mesh geometry={nodes.Cylinder_Inner_Light_case_0.geometry} material={materials.Inner_Light_case} />
            <mesh geometry={nodes.Cylinder_Inner_light_emission_0.geometry} material={materials.Inner_light_emission} />
          </group>
          <group position={[-0.475, 364.929, -79.019]} rotation={[-Math.PI / 2, 0, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder001_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder001_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[-244.636, 364.929, -79.019]} rotation={[-Math.PI / 2, -0.322, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder002_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder002_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[243.686, 364.929, -79.019]} rotation={[-Math.PI / 2, 0.291, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder003_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder003_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[-244.636, 364.929, 122.199]} rotation={[-Math.PI / 2, -0.211, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder004_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder004_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[-0.475, 364.929, 122.199]} rotation={[-Math.PI / 2, 0, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder005_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder005_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[243.686, 364.929, 122.199]} rotation={[-1.465, 0.287, -0.38]} scale={7.313}>
            <mesh geometry={nodes.Cylinder006_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder006_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[-244.636, 364.929, -285.145]} rotation={[-Math.PI / 2, -0.339, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder007_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder007_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[-0.475, 364.929, -285.145]} rotation={[-Math.PI / 2, 0, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder008_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder008_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[243.686, 364.929, -285.145]} rotation={[-Math.PI / 2, 0, 0]} scale={7.313}>
            <mesh geometry={nodes.Cylinder009_Light_Case_0.geometry} material={materials.Light_Case} />
            <mesh geometry={nodes.Cylinder009_Light_emission_0.geometry} material={materials.Light_emission} />
          </group>
          <group position={[-53.651, 132.925, 46.362]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={4.887}>
            <mesh geometry={nodes['Monitor_27_Curved002_PC-1Back_Panel_0'].geometry} material={materials['PC-1Back_Panel']} />
            <mesh geometry={nodes['Monitor_27_Curved002_PC-1Stand_0'].geometry} material={materials['PC-1Stand']} />
            <mesh geometry={nodes['Monitor_27_Curved002_PC-1Wallpaper_0'].geometry} material={materials['PC-1Wallpaper']} />
          </group>
          <group position={[-388.953, 196.332, -746.637]} scale={[48.538, 41.777, 39.57]}>
            <mesh geometry={nodes.Plane004_Black_Frame_Window001_0.geometry} material={materials['Black_Frame_Window.001']} />
            <mesh geometry={nodes.Plane004_Window_Glass001_0.geometry} material={materials['Window_Glass.001']} />
          </group>
          <group position={[520.768, 213.61, -608.052]} rotation={[0, -1.571, 0]} scale={[48.538, 41.777, 39.57]}>
            <mesh geometry={nodes.Plane006_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} />
            <mesh geometry={nodes.Plane006_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group position={[0, 0, -100.308]} rotation={[-Math.PI / 2, 0, 0]} scale={[515.103, 398.369, 398.369]}>
            <mesh geometry={nodes.Plane007_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Plane007_Material008_0.geometry} material={materials['Material.008']} />
          </group>
          <group position={[-520.382, 199.865, 447.513]} rotation={[0, 1.571, 0]} scale={[48.538, 41.777, 39.57]}>
            <mesh geometry={nodes.Plane009_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} />
            <mesh geometry={nodes.Plane009_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group position={[543.958, 172.648, 409.438]} rotation={[0, -1.571, 0]} scale={[48.538, 41.777, 39.57]}>
            <mesh geometry={nodes.Plane012_Bathroom_door_opaque_0.geometry} material={materials.Bathroom_door_opaque} />
            <mesh geometry={nodes.Plane012_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} />
          </group>
          <group position={[0, 0, -100.308]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane015_Wall_Rim_0.geometry} material={materials.Wall_Rim} />
            <mesh geometry={nodes.Plane015_Wall_0.geometry} material={materials.Wall} />
          </group>
          <group position={[-522.979, 196.332, -25.769]} rotation={[0, 1.571, 0]} scale={[48.538, 41.777, 39.57]}>
            <mesh geometry={nodes.Plane020_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} />
            <mesh geometry={nodes.Plane020_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group position={[87.241, 97.398, 7.543]} rotation={[-Math.PI / 2, 0, 1.834]} scale={1.237}>
            <mesh geometry={nodes.R_Mouse_00001_PC2_BODY_0.geometry} material={materials.PC2_BODY} />
            <mesh geometry={nodes.R_Mouse_00001_PC2_SCREEN_0.geometry} material={materials.PC2_SCREEN} />
          </group>
          <group position={[165.531, 135.211, 385.731]} rotation={[0, 1.571, 0]} scale={43.618}>
            <mesh geometry={nodes.Rectangle013001_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Rectangle013001_Marble_0.geometry} material={materials.Marble} />
            <mesh geometry={nodes.Rectangle013001_Material020_0.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Rectangle013001_Material055_0.geometry} material={materials['Material.055']} />
          </group>
          <group position={[56.094, 110.061, -259.265]} rotation={[0, 1.571, 0]} scale={1.702}>
            <mesh geometry={nodes.surface_SURFACE_2_KEYBOARD_0.geometry} material={materials.SURFACE_2_KEYBOARD} />
            <mesh geometry={nodes.surface_SURFACE_2_SCREEN_0.geometry} material={materials.SURFACE_2_SCREEN} />
          </group>
          <group position={[56.094, 110.061, -259.265]} rotation={[0, 1.571, 0]} scale={1.702}>
            <mesh geometry={nodes.surface001_SURFACE_1_KEYBOARD_0.geometry} material={materials.SURFACE_1_KEYBOARD} />
            <mesh geometry={nodes.surface001_SURFACE_1_SCREEN_0.geometry} material={materials.SURFACE_1_SCREEN} />
          </group>
          <group position={[-91.47, 95.896, -232.847]} rotation={[-1.596, 0.245, -1.468]} scale={41.664}>
            <mesh geometry={nodes.tela_LAP_1_BLACK_FRAME_0.geometry} material={materials.LAP_1_BLACK_FRAME} />
            <mesh geometry={nodes.tela_LAP_1_BODY_0.geometry} material={materials.LAP_1_BODY} />
            <mesh geometry={nodes.tela_LAP_1_KEYBOARD_0.geometry} material={materials.LAP_1_KEYBOARD} />
            <mesh geometry={nodes.tela_LAP_1SCREEN_0.geometry} material={materials.LAP_1SCREEN} />
          </group>
          <group position={[364.786, 174.615, 561.623]} rotation={[0, 1.571, 0]} scale={[110.631, 153.836, 110.631]}>
            <mesh geometry={nodes.wallpictures001_Other_BUddha_frame_0.geometry} material={materials.Other_BUddha_frame} />
            <mesh geometry={nodes.wallpictures001_Other_BUdhha001_0.geometry} material={materials['Other_BUdhha.001']} />
          </group>
          <group position={[512.488, 226.051, -221.782]} rotation={[Math.PI, 0, Math.PI]} scale={[119.579, 166.278, 119.579]}>
            <mesh geometry={nodes.wallpictures003_Other_BUddha_frame_0.geometry} material={materials.Other_BUddha_frame} />
            <mesh geometry={nodes.wallpictures003_Other_BUdhha_0.geometry} material={materials.Other_BUdhha} />
          </group>
          <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube__0} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_Light_Fixture_0.geometry} material={materials.Light_Fixture} position={[-243.376, 374.575, -81.939]} rotation={[-Math.PI / 2, 0, 0]} scale={[17.475, 221.057, 14.36]} />
          <mesh geometry={nodes.low_poly001_PC2_CUP_0.geometry} material={materials.PC2_CUP} position={[-96.934, 104.672, -179.34]} rotation={[Math.PI, -1.218, Math.PI]} scale={104.361} />
          <mesh geometry={nodes.low_poly012_Black5001_0.geometry} material={materials['Black5.001']} position={[89.963, 21.688, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.low_poly013_Green1_0.geometry} material={materials.Green1} position={[89.963, 21.688, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.low_poly014_Black5_0.geometry} material={materials.Black5} position={[928.261, 144.487, -287.716]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.low_poly018_PC2_CUP_0.geometry} material={materials.PC2_CUP} position={[-96.934, 104.672, -9.247]} rotation={[Math.PI, -1.218, Math.PI]} scale={104.361} />
          <mesh geometry={nodes.low_poly025_Blue3_0.geometry} material={materials.Blue3} position={[89.963, 21.688, 0]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Mirror_Chrome001_0.geometry} material={materials['Chrome.001']} position={[114.094, 229.585, 423.474]} rotation={[0, 1.571, 0]} scale={[88.69, 71.932, 71.932]} />
          <mesh geometry={nodes.Monitor_27_Curved001_PC1MOUSE_PAD_0.geometry} material={materials.PC1MOUSE_PAD} position={[-98.322, 98.079, 66.16]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={4.887} />
          <mesh geometry={nodes['Monitor_27_Curved003_PC-1_Keyboard_0'].geometry} material={materials['PC-1_Keyboard']} position={[-100.191, 98.17, 38.896]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={4.887} />
          <mesh geometry={nodes.Monitor_27_Curved004_PC1MOUSE_0.geometry} material={materials.PC1MOUSE} position={[-98.322, 98.079, 66.16]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={4.887} />
          <mesh geometry={nodes.Plane_Material003_0.geometry} material={materials['Material.003']} position={[1.104, 94.98, -60.764]} rotation={[-Math.PI / 2, 0, 0]} scale={[129.712, 201.896, 100]} />
          <mesh geometry={nodes.Plane001_Roof_0.geometry} material={materials.Roof} position={[-21.744, 363.68, -65.287]} rotation={[-Math.PI / 2, 0, 0]} scale={[105.553, 105.552, 105.552]} />
          <mesh geometry={nodes.Plane002_White_0.geometry} material={materials.White} rotation={[Math.PI, 0, 0]} scale={[264.514, 195.858, 100]} />
          <mesh geometry={nodes.Plane003_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} position={[-291.837, 406.102, -729.952]} scale={[39.626, 43.596, 41.484]} />
          <mesh geometry={nodes.Plane005_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} position={[530.865, 406.102, -594.362]} rotation={[0, 1.571, 0]} scale={[39.626, 43.596, 27.591]} />
          <mesh geometry={nodes.Plane008_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} position={[-530.479, 392.357, 433.823]} rotation={[0, -1.571, 0]} scale={[39.626, 43.596, 27.591]} />
          <mesh geometry={nodes.Plane010_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} position={[-506.293, 406.102, -122.885]} rotation={[0, 1.571, 0]} scale={[39.626, 43.596, 41.484]} />
          <mesh geometry={nodes.Plane011_Black_Frame_Window_0.geometry} material={materials.Black_Frame_Window} position={[539.604, 204.942, 441.675]} rotation={[0, 1.571, 0]} scale={[39.626, 43.596, 27.591]} />
          <mesh geometry={nodes.Plane013_Floor_0.geometry} material={materials.Floor} position={[0, 1.545, -100.308]} rotation={[-Math.PI / 2, 0, 0]} scale={103.318} />
          <mesh geometry={nodes.Plane014_Material002_0.geometry} material={materials['Material.002']} position={[0, 0, -100.308]} rotation={[-Math.PI / 2, 0, 0]} scale={[515.103, 398.369, 398.369]} />
          <mesh geometry={nodes.Plane016_Material001_0.geometry} material={materials['Material.001']} position={[2.5, 2.508, -554.031]} rotation={[-Math.PI / 2, 0, 0]} scale={[106.229, 170.858, 100]} />
          <mesh geometry={nodes.R_Mouse_00002_PC2_MOUSEPAD_0.geometry} material={materials.PC2_MOUSEPAD} position={[92.88, 98.081, 42.961]} rotation={[-Math.PI / 2, 0, 1.834]} scale={1.237} />
          <mesh geometry={nodes.R_Mouse_00003_PC2_KEYBOARD_0.geometry} material={materials.PC2_KEYBOARD} position={[94.34, 98.17, 59.888]} rotation={[-Math.PI / 2, 0, 1.834]} scale={1.237} />
          <mesh geometry={nodes.R_Mouse_00004_PC2_MOUSE_0.geometry} material={materials.PC2_MOUSE} position={[92.88, 98.081, 42.961]} rotation={[-Math.PI / 2, 0, 1.834]} scale={1.237} />
          <mesh geometry={nodes.Soap_1_Cylinder001_bottle_base_0.geometry} material={materials.bottle_base} position={[141.075, 156.257, 454.893]} rotation={[-Math.PI, 0.526, -Math.PI]} scale={11.088} />
          <mesh geometry={nodes.Soap_2_Cylinder001_bottle_top_0.geometry} material={materials.bottle_top} position={[142.89, 167.136, 455.22]} rotation={[-Math.PI, 0.526, -Math.PI]} scale={11.088} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/office.glb')
